[project]
authors = [ {name = "Andrey Korzh", email = "ao.korzh@gmail.com"} ]
description = "saving to the pandas HDF5 store"
name = "absioras-hdf5_pandas"
requires-python = ">= 3.11"
version = "0.1.0"
dependencies = []

[project.optional-dependencies]
test = ["pytest"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.wheel]
packages = ["src/hdf5_pandas"]

[tool.pixi.pypi-dependencies]
# Подмодули автоматически доступны через workspace

[tool.hatch.envs.test]
dependencies = ["pytest"]

[tool.hatch.envs.test.scripts]
test = "pytest tests/"

[tool.ruff]
line-length = 110
