[project]
description = "Monorepo for oceanology projects"
authors = [{name = "Andrey Korzh", email = "ao.korzh@gmail.com"}]
name = "absioras"
requires-python = ">= 3.11"
version = "0.1.0"
dependencies = [
"hydra-colorlog",
"wmm2020",
"ruamel-yaml>=0.19.1"
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.workspace]
members = [
    "oceano/*",
    "shared/*"
]

[tool.hatch.build.targets.wheel]
packages = [
"oceano/adcp", "oceano/gps_tracker", "oceano/tcm", "oceano/ctd", "oceano/get_datasets", "shared/utils", "shared/hdf5_pandas", "shared/hdf5_alt",
"third_party/descartes", "third_party/veusz", "third_party/mne", "third_party/wafo"
]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64"]

[tool.pixi.pypi-dependencies]
absioras-adcp  = { path = "oceano/adcp", editable = true }
absioras-gps_tracker  = { path = "oceano/gps_tracker", editable = true }
absioras-tcm  = { path = "oceano/tcm", editable = true }
absioras-ctd  = { path = "oceano/ctd", editable = true }
absioras-get_datasets  = { path = "oceano/get_datasets", editable = true }
absioras-utils = { path = "shared/utils", editable = true }
absioras-hdf5_pandas = { path = "shared/hdf5_pandas", editable = true }
absioras-hdf5_alt = { path = "shared/hdf5_alt", editable = true }
absioras-veusz_helpers = { path = "shared/veusz_helpers", editable = true }
absioras-third_party-descartes = { path = "third_party/descartes", editable = true }
absioras-third_party-veusz = { path = "third_party/veusz", editable = true }
absioras-third_party-mne = { path = "third_party/mne", editable = true }
absioras-third_party-wafo = { path = "third_party/wafo", editable = true }


# Зависимости сервисов как features
[tool.pixi.feature.get_datasets]
dependencies = { copernicusmarine = "*" }


[tool.pixi.tasks]
test = "pytest tests/"
test-all = "hatch run test:*"

# Окружения
[tool.pixi.environments]
default = ["get_datasets", "dev", "script"]

[tool.pixi.feature.dev.dependencies]
pytest = "*"

[tool.pixi.feature.script.dependencies]
jupyterlab = "*"
jupyterlab-spellchecker = "*"
nb_conda = "*"
nbconvert = "*"
sympy = "*"
cvxpy = "*"
pixi-kernel = "*"
seaborn = "*"

[tool.pixi.dependencies]
antlr = "*"
attrs = "*"
blosc = "*"
bokeh = "*"
bqplot = "*"
cachey = "*"
cdsapi = "*"
chardet = "*"
clize = "*"
colorama = "*"
colorlog = "*"
dask = "*"
dask-funk = "*"
dtale = "*"
frictionless = "*"
ftputil = "*"
gdal = "*"
geopandas = "*"
google-api-python-client = "*"
google-auth-oauthlib = "*"
gpxpy = "*"
gsw = "*"
h5py = "*"
hdf5 = "*"
hydra-core = "*"
json2html = "*"
lxml = "*"
matplotlib = "*"
more-itertools = "*"
motuclient = "*"
netcdf4 = "*"
numpy = "<2.4"
numba = "*"
numexpr = "*"
openssl = "*"
pandas = "*"
pillow = "*"
polars = "*"
progressbar2 = "*"
py = "*"
py7zr = "*"
pyinstaller = "*"
pyinstaller-hooks-contrib = "*"
pynmea2 = "*"
pyproj = "*"
pyodbc = "*"
pyqt = "*"
pytables = "*"
pytest = "*"
pytest-arraydiff = "*"
pywavelets = "*"
pywin32 = "*"
qt = "*"
rarfile = "*"
re2 = "*"
requests = "*"
scikit-learn = "*"
scipy = "*"
selenium = "*"
shapely = "*"
snappy = "*"
sqlite = "*"
statsmodels = "*"
tabulate = "*"
toolz = "*"
tqdm = "*"
urllib3 = "*"
xarray = "*"
webdriver-manager = "*"
astropy = "*"
cfgrib = "*"
wavespectra = ">=4.4.2"
questionary = ">=2.1.1"

[tool.ruff]
line-length = 110
target-version = "py312"
builtins = ["SetData", "SetData2D", "SetDataExpression", "SetData2DExpression", "SetData2DExpressionXYZ", "SetData2DXYFunc", "AddCustom", "DatasetPlugin", "TagDatasets", "Add", "To", "Set", "CreateHistogram", "FilterDatasets", "ImportFileCSV"]
