[pytest]
testpaths =
    oceano/get_datasets/
    oceano/meta_finder/
    oceano/tcm/
    shared/veusz_helpers/
    tests/
addopts = --import-mode importlib
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
markers =
    calibration: calibration math tests
    legacy: legacy pipeline tests
