"""
Test to verify that duplicate device IDs are not created when merging from info_devices.yaml.

This test specifically addresses the bug where devices from info_devices.yaml with
non-normalized IDs (e.g., "I03", "incl03") would be added as duplicates
when the normalized form (e.g., "i03") already existed in the merged content.
"""
import pytest
from pathlib import Path
from meta_finder.create_info_files import update_devices_meta_file, _merge_device_metadata
from meta_finder.io_info_files import read_metadata_file
from meta_finder.config import DEVICES_FILE_NAME_YAML, DEVICES_FILE_NAME_UPD


@pytest.fixture
def temp_device_dir(tmp_path):
    """Create a temporary device directory for testing."""
    device_dir = tmp_path / "test_device"
    device_dir.mkdir()
    return device_dir


@pytest.fixture
def info_yaml_with_non_normalized_ids(temp_device_dir):
    """
    Create an info_devices.yaml file with non-normalized device IDs.
    This simulates the scenario where a user manually created or edited
    info_devices.yaml with different case or full device names.
    """
    yaml_file = temp_device_dir / DEVICES_FILE_NAME_YAML
    yaml_content = {
        "I03": ["?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?"],
        "incl04": ["?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?"],
        "W01": ["?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?"],
    }

    # Use io_info_files to write the YAML file
    from meta_finder.io_info_files import save_to_yaml_format
    save_to_yaml_format(yaml_content, yaml_file)

    return yaml_file


@pytest.fixture
def new_content_with_normalized_ids():
    """
    Create new content with normalized device IDs (no leading zeros).
    This simulates the content generated by the metadata extraction process,
    which always uses normalized IDs via normalize_device_id().
    """
    return {
        "i3": {
            "point": "1",
            "sea_depth": "10",
            "height_above_bottom": "5",
            "modification_symbol": "",
            "latitude": "55.5",
            "longitude": "21.5",
            "time_st": "2023-01-01 00:00:00",
            "time_en": "2023-01-02 00:00:00",
            "burst_dt": "300",
            "bursts_t": "10",
            "comment": "Test device",
        },
        "i4": {
            "point": "2",
            "sea_depth": "15",
            "height_above_bottom": "7",
            "modification_symbol": "",
            "latitude": "55.6",
            "longitude": "21.6",
            "time_st": "2023-01-01 00:00:00",
            "time_en": "2023-01-02 00:00:00",
            "burst_dt": "300",
            "bursts_t": "10",
            "comment": "Test device 2",
        },
        "w1": {
            "point": "3",
            "sea_depth": "20",
            "height_above_bottom": "10",
            "modification_symbol": "",
            "latitude": "55.7",
            "longitude": "21.7",
            "time_st": "2023-01-01 00:00:00",
            "time_en": "2023-01-02 00:00:00",
            "burst_dt": "600",
            "bursts_t": "5",
            "comment": "Test device 3",
        },
    }


def test_no_duplicate_device_ids_from_yaml(
    temp_device_dir,
    info_yaml_with_non_normalized_ids,
    new_content_with_normalized_ids
):
    """
    Test that update_devices_meta_file does not create duplicate device IDs
    when merging from info_devices.yaml with non-normalized IDs.

    Scenario:
    1. info_devices.yaml has: I03, incl04, W01 (non-normalized)
    2. New content has: i3, i4, w1 (normalized via normalize_device_id)
    3. Expected result: i3, i4, w1 (normalized, no duplicates)
    """
    # Call update_devices_meta_file to merge the content
    result = update_devices_meta_file(
        device_dir=temp_device_dir,
        content=new_content_with_normalized_ids
    )

    # Verify that the file was created/updated
    assert result is True, "update_devices_meta_file should return True"

    # Read the created file
    output_file = temp_device_dir / DEVICES_FILE_NAME_UPD
    assert output_file.exists(), "Output file should exist"

    output_content = read_metadata_file(output_file)

    # Verify that we have exactly 3 devices (not 6)
    assert len(output_content) == 3, (
        f"Expected 3 devices in output, got {len(output_content)}. "
        f"Devices: {list(output_content.keys())}"
    )

    # Verify that all device IDs are normalized (no leading zeros)
    expected_device_ids = {"i3", "i4", "w1"}
    actual_device_ids = set(output_content.keys())

    assert actual_device_ids == expected_device_ids, (
        f"Expected normalized device IDs {expected_device_ids}, "
        f"got {actual_device_ids}"
    )

    # Verify that non-normalized IDs are NOT present
    assert "I03" not in actual_device_ids, "Non-normalized 'I03' should not be present"
    assert "incl04" not in actual_device_ids, "Non-normalized 'incl04' should not be present"
    assert "W01" not in actual_device_ids, "Non-normalized 'W01' should not be present"


def test_merge_device_metadata_helper_function():
    """
    Test the _merge_device_metadata helper function directly to ensure
    it correctly handles normalization and prevents duplicates.
    """
    # Existing content with normalized IDs (same as in info_devices@meta_finder.yaml)
    existing_content = {
        "i03": ["?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?"],
        "i04": ["?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?"],
    }

    # New content with normalized IDs (same devices, updated values)
    new_content = {
        "i03": ["1", "10", "5", "", "55.5", "21.5", "2023-01-01 00:00:00",
                 "2023-01-02 00:00:00", "300", "10", "Test"],
        "i04": ["2", "15", "7", "", "55.6", "21.6", "2023-01-01 00:00:00",
                 "2023-01-02 00:00:00", "300", "10", "Test2"],
        "w01": ["3", "20", "10", "", "55.7", "21.7", "2023-01-01 00:00:00",
                 "2023-01-02 00:00:00", "600", "5", "Test3"],
    }

    # Merge with normalize_keys=False (as when merging from existing info_devices@meta_finder.yaml)
    merged = _merge_device_metadata(
        existing_content,
        new_content,
        normalize_keys=False
    )

    # Verify no duplicates
    assert len(merged) == 3, (
        f"Expected 3 devices after merge, got {len(merged)}. "
        f"Devices: {list(merged.keys())}"
    )

    # Verify all IDs are present
    expected_ids = {"i03", "i04", "w01"}
    actual_ids = set(merged.keys())
    assert actual_ids == expected_ids, (
        f"Expected IDs {expected_ids}, got {actual_ids}"
    )

    # Verify that merged content has the new values (not placeholders)
    # Merged devices get nested station dict structure: {"0": [values]}
    assert merged["i03"]["0"][0] == "1", "i03 should have new point value"
    assert merged["i04"]["0"][0] == "2", "i04 should have new point value"
    assert merged["w01"][0] == "3", "w01 should have new point value (new device, flat list)"


def test_merge_device_metadata_without_normalization():
    """
    Test the _merge_device_metadata helper function with normalize_keys=False
    (as when merging from existing info_devices@meta_finder.yaml).
    This test verifies that devices are not duplicated when merging.
    """
    # Existing content with normalized IDs
    existing_content = {
        "i03": ["?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?"],
        "i04": ["?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?"],
    }

    # New content with normalized IDs (same devices, updated values)
    new_content = {
        "i03": ["1", "10", "5", "", "55.5", "21.5", "2023-01-01 00:00:00",
                 "2023-01-02 00:00:00", "300", "10", "Test"],
        "i04": ["2", "15", "7", "", "55.6", "21.6", "2023-01-01 00:00:00",
                 "2023-01-02 00:00:00", "300", "10", "Test2"],
        "w01": ["3", "20", "10", "", "55.7", "21.7", "2023-01-01 00:00:00",
                 "2023-01-02 00:00:00", "600", "5", "Test3"],
    }

    # Merge with normalize_keys=False
    merged = _merge_device_metadata(
        existing_content,
        new_content,
        normalize_keys=False
    )

    # Verify no duplicates - this is the key test for the bug fix
    assert len(merged) == 3, (
        f"Expected 3 devices after merge, got {len(merged)}. "
        f"Devices: {list(merged.keys())}. "
        f"BUG: Devices were duplicated!"
    )

    # Verify that merged content has the new values
    # Merged devices get nested station dict structure: {"0": [values]}
    assert merged["i03"]["0"][0] == "1", "i03 should have new point value"
    assert merged["i04"]["0"][0] == "2", "i04 should have new point value"
    assert merged["w01"][0] == "3", "w01 should have new point value (new device, flat list)"


def test_partial_update_preserves_non_placeholder_values(
    temp_device_dir,
    info_yaml_with_non_normalized_ids
):
    """
    Test that when merging, non-placeholder values from existing YAML
    are preserved even when new content has placeholders.
    """
    # Create new content with normalized IDs (i3, i4) matching normalize_device_id output.
    # i3 has placeholder time values so existing YAML non-placeholders should be preserved.
    new_content = {
        "i3": {
            "point": "1",
            "sea_depth": "10",
            "height_above_bottom": "5",
            "modification_symbol": "",
            "latitude": "55.5",
            "longitude": "21.5",
            "time_st": "?",  # Placeholder — existing YAML value should be kept
            "time_en": "?",  # Placeholder — existing YAML value should be kept
            "burst_dt": "?",
            "bursts_t": "?",
            "comment": "Test device",
        },
        "i4": {
            "point": "2",
            "sea_depth": "15",
            "height_above_bottom": "7",
            "modification_symbol": "",
            "latitude": "55.6",
            "longitude": "21.6",
            "time_st": "2023-01-01 00:00:00",
            "time_en": "2023-01-02 00:00:00",
            "burst_dt": "300",
            "bursts_t": "10",
            "comment": "Test device 2",
        },
    }

    # Update the YAML file to have non-placeholder time values for I03
    yaml_file = temp_device_dir / DEVICES_FILE_NAME_YAML
    from meta_finder.io_info_files import save_to_yaml_format
    yaml_content = {
        "I03": ["?", "?", "?", "?", "?", "?",
                  "2023-01-01 00:00:00",  # Non-placeholder
                  "2023-01-02 00:00:00",  # Non-placeholder
                  "?", "?", "?"],
        "incl04": ["?", "?", "?", "?", "?", "?", "?", "?", "?", "?", "?"],
    }
    save_to_yaml_format(yaml_content, yaml_file)

    # Call update_devices_meta_file
    result = update_devices_meta_file(
        device_dir=temp_device_dir,
        content=new_content
    )

    assert result is True, "update_devices_meta_file should return True"

    # Read the created file
    output_file = temp_device_dir / DEVICES_FILE_NAME_UPD
    output_content = read_metadata_file(output_file)

    # Verify exactly 2 devices (no duplicates from normalization mismatch)
    assert len(output_content) == 2, (
        f"Expected 2 devices, got {len(output_content)}: {list(output_content.keys())}"
    )

    # Verify that i3 has the non-placeholder time values from YAML preserved
    i3_data = output_content["i3"]
    assert i3_data["0"][6] == "2023-01-01 00:00:00", (
        "i3 should preserve non-placeholder time_st from YAML"
    )
    assert i3_data["0"][7] == "2023-01-02 00:00:00", (
        "i3 should preserve non-placeholder time_en from YAML"
    )

    # Verify that i4 has the new values from new_content
    i4_data = output_content["i4"]
    assert i4_data["0"][0] == "2", "i4 should have new point value"
    assert i4_data["0"][6] == "2023-01-01 00:00:00", "i4 should have new time_st value"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
