"""Test that metadata from info_devices.yaml is used in TSV output files.

This test verifies that when info_devices.yaml exists, its metadata is properly
included in the TSV output files generated by the metadata processing workflow.
"""

from pathlib import Path

import pytest

from meta_finder.metadata_extractor import read_metadata_files_to_dict
from meta_finder.io_info_files import write_metadata_file, read_metadata_file


@pytest.mark.parametrize(
    "test_case,expected_comment",
    [
        (
            "yaml_metadata_used_in_tsv",
            "Comment from YAML file",
        ),
    ],
    ids=["yaml_metadata_used_in_tsv"],
)
def test_yaml_metadata_used_in_tsv_outputs(test_case: str, expected_comment: str, tmp_path: Path):
    """Test that metadata from info_devices.yaml is included in TSV outputs.

    This test creates a test device directory with info_devices.yaml containing
    metadata, then verifies that the metadata is read correctly.

    Args:
        test_case: Identifier for the test case
        expected_comment: Expected comment value from YAML file
        tmp_path: Temporary directory fixture
    """
    # Setup test device directory with YAML metadata
    device_dir = tmp_path / "test_device"
    device_dir.mkdir(parents=True, exist_ok=True)

    # Create info_devices.yaml with metadata
    yaml_content = {
        "i01": [
            "point1",  # point
            "100.0",  # sea_depth
            "50.0",  # height_above_bottom
            "",  # modification_symbol
            "60.12345",  # lat
            "25.67890",  # lon
            "2024-01-01 10:00:00",  # time_st
            "2024-01-01 11:00:00",  # time_en
            "",  # burst_dt
            "",  # bursts_t
            "Comment from YAML file",  # comment
        ]
    }

    # Write YAML file
    yaml_file = device_dir / "info_devices.yaml"
    write_metadata_file(device_dir, yaml_file, yaml_content)

    # Read metadata using the same function that process_all_metadata uses
    json_path = device_dir / "info_devices.json"
    result = read_metadata_files_to_dict(json_path)

    # Verify that metadata from YAML file was read
    assert result is not None, "Metadata should not be None"
    assert len(result) == 1, f"Expected 1 device, got {len(result)}"

    # Device ID is normalized from "i01" to "i1" by normalize_device_id function
    assert "i1" in result, "Device i1 (normalized from i01) not found in metadata"

    # read_metadata_files_to_dict returns {device_id: {"0": {field_name: value}}}
    # Access station "0" for single-interval device
    device_meta = result["i1"]["0"]

    # Verify that the comment from YAML file is present
    assert device_meta["comment"] == expected_comment, (
        f"Expected comment '{expected_comment}', got '{device_meta['comment']}'"
    )

    # Verify other metadata fields from YAML
    assert device_meta["lat"] == "60.12345", (
        f"Expected lat '60.12345', got '{device_meta['lat']}'"
    )
    assert device_meta["lon"] == "25.67890", (
        f"Expected lon '25.67890', got '{device_meta['lon']}'"
    )
    assert device_meta["sea_depth"] == "100.0", (
        f"Expected sea_depth '100.0', got '{device_meta['sea_depth']}'"
    )


def test_yaml_metadata_priority_over_json_in_tsv(tmp_path: Path):
    """Test that YAML metadata takes priority over JSON metadata in TSV outputs.

    When both info_devices.yaml and info_devices.json exist, the YAML metadata
    should be used in the TSV output.

    Args:
        tmp_path: Temporary directory fixture
    """
    # Setup test device directory with both YAML and JSON metadata
    device_dir = tmp_path / "test_device"
    device_dir.mkdir(parents=True, exist_ok=True)

    # Create info_devices.yaml with metadata
    yaml_content = {
        "i01": [
            "point1",  # point
            "100.0",  # sea_depth
            "50.0",  # height_above_bottom
            "",  # modification_symbol
            "60.12345",  # lat
            "25.67890",  # lon
            "2024-01-01 10:00:00",  # time_st
            "2024-01-01 11:00:00",  # time_en
            "",  # burst_dt
            "",  # bursts_t
            "Comment from YAML",  # comment
        ]
    }

    # Write YAML file
    yaml_file = device_dir / "info_devices.yaml"
    write_metadata_file(device_dir, yaml_file, yaml_content)

    # Create info_devices.json with DIFFERENT metadata
    json_content = {
        "i01": [
            "point2",  # point (different)
            "200.0",  # sea_depth (different)
            "60.0",  # height_above_bottom (different)
            "",  # modification_symbol
            "70.12345",  # lat (different)
            "35.67890",  # lon (different)
            "2024-01-01 12:00:00",  # time_st (different)
            "2024-01-01 13:00:00",  # time_en (different)
            "",  # burst_dt
            "",  # bursts_t
            "Comment from JSON",  # comment (different)
        ]
    }

    # Write JSON file
    json_file = device_dir / "info_devices.json"
    write_metadata_file(device_dir, json_file, json_content)

    # Read metadata using the same function that process_all_metadata uses
    result = read_metadata_files_to_dict(json_file)

    # Verify that YAML metadata was used instead of JSON metadata
    assert result is not None, "Metadata should not be None"

    # Access station "0" for single-interval device
    device_meta = result["i1"]["0"]

    # Device ID is normalized from "i01" to "i1" by normalize_device_id function
    assert device_meta["comment"] == "Comment from YAML", (
        f"Expected YAML comment 'Comment from YAML', got '{device_meta['comment']}'"
    )
    assert device_meta["lat"] == "60.12345", (
        f"Expected YAML lat '60.12345', got '{device_meta['lat']}'"
    )
    assert device_meta["sea_depth"] == "100.0", (
        f"Expected YAML sea_depth '100.0', got '{device_meta['sea_depth']}'"
    )
