"""HTTP serving side of the local documentation browser.

Locations — identical in dev repo and frozen ``_MEIPASS`` (the frozen tree
mirrors the dev repo, see ``spec_common.collect_docs``):

- :data:`_WEB_DIR` — first-party viewer page (``web/`` inside this package
  = ``src/tcm_gui/browser/web``), bundled with ``tcm_gui`` automatically;
- :data:`_VEND_DIR` — generated third-party runtime at
  ``<project>/_build/browser-runtime`` (see ``browser/vendor.mjs``), mounted
  under ``/assets/``; the project dir comes from the same
  ``PROJECT_ROOT.parents[1]`` formula as :data:`tcm._constants.DOC_DIR`.

Only these fixed locations and ``/api/document`` / ``/api/asset``
(validated against ``allowed_roots``) are reachable — nothing else leaks.
"""

from __future__ import annotations

import http.server
import json
import urllib.parse
from pathlib import Path

from tcm._constants import PROJECT_ROOT

# ─────────────────────────────────────────────────────────────────────────────
# Document classification (mirrored browser-side in web/viewer.js)
# ─────────────────────────────────────────────────────────────────────────────

_MARKDOWN_EXT = {".md", ".markdown"}

_SOURCE_LANG: dict[str, str] = {  # extension (sans dot) → highlight.js language; repo-present only
    "py": "python",
    "pyi": "python",
    "js": "javascript",
    "mjs": "javascript",
    "cjs": "javascript",
    "css": "css",
    "html": "xml",
    "htm": "xml",
    "xml": "xml",
    "json": "json",
    "yaml": "yaml",
    "yml": "yaml",
    "toml": "toml",
    "ini": "ini",
    "cfg": "ini",
    "txt": "plaintext",
    "log": "plaintext",
    "ps1": "powershell",
    "bat": "dos",
    "cmd": "dos",
    "sh": "shell",
}

_IMAGE_MIME = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".webp": "image/webp",
    ".svg": "image/svg+xml",
    ".bmp": "image/bmp",
    ".ico": "image/x-icon",
    ".avif": "image/avif",
}


def _kind_of(path: Path) -> str | None:
    """Document class by extension: ``markdown`` / ``source`` / ``image`` / None."""
    if (suffix := path.suffix.lower()) in _MARKDOWN_EXT:
        return "markdown"
    if suffix.removeprefix(".") in _SOURCE_LANG:
        return "source"
    if suffix in _IMAGE_MIME:
        return "image"
    return None


# ─────────────────────────────────────────────────────────────────────────────
# Static locations & routes
# ─────────────────────────────────────────────────────────────────────────────

_WEB_DIR = Path(__file__).resolve().parent / "web"  # index.html, viewer.js, viewer.css
# Project dir (oceano/tcm) in both layouts — same parents[1] formula as DOC_DIR
_VEND_DIR = PROJECT_ROOT.parents[1] / "_build" / "browser-runtime"  # generated by browser/vendor.mjs

_VIEWER_FILES: dict[str, tuple[str, str]] = {  # URL → (file under _WEB_DIR, content type)
    "/": ("index.html", "text/html; charset=utf-8"),
    "/index.html": ("index.html", "text/html; charset=utf-8"),
    "/viewer.js": ("viewer.js", "text/javascript; charset=utf-8"),
    "/viewer.css": ("viewer.css", "text/css; charset=utf-8"),
}

_ASSET_CTYPE = {
    ".js": "text/javascript",
    ".woff2": "font/woff2",
    ".css": "text/css",
    ".json": "application/json",
}


def _rel_error(path: Path, root: Path) -> ValueError | None:
    """Return ValueError if *path* is not relative to *root*, else None."""
    try:
        path.relative_to(root)
        return None
    except ValueError as e:
        return e


def _dir_listing(directory: Path, *, show_source: bool = False) -> dict:
    """Immediate children of *directory* as relative hrefs for the viewer.

    Only markdown files by default (the browser's document classes); with
    ``show_source`` also the ``_SOURCE_LANG`` files.  Subfolders keep a filesystem
    path too — the viewer resolves a trailing-slash href against the current
    document, so relative ``href`` (+ ``path`` for the API round-trip) suffices.
    """
    folders = sorted(p for p in directory.iterdir() if p.is_dir())
    files = sorted(
        p
        for p in directory.iterdir()
        if p.is_file()
        and (p.suffix.lower() in _MARKDOWN_EXT or (show_source and p.suffix[1:].lower() in _SOURCE_LANG))
    )
    return {
        "kind": "directory",
        "path": str(directory),
        "name": directory.name,
        "directories": [{"name": p.name, "href": p.name + "/"} for p in folders],
        "files": [{"name": p.name, "href": p.name} for p in files],
    }


class _Handler(http.server.BaseHTTPRequestHandler):
    """Serve the viewer, documents (JSON) and images from approved roots."""

    server_version = "TkDocumentationBrowser/1.0"

    def log_message(self, format: str, *args) -> None:
        """Suppress default HTTP request logging (use our logger)."""

    @property
    def _app(self) -> DocumentationBrowser:
        return self.server.app  # type: ignore[attr-defined]

    def _send(self, body: str, *, status: int = 200, ctype: str = "text/plain; charset=utf-8") -> None:
        self._send_bytes(body.encode("utf-8"), status=status, ctype=ctype)

    def _send_bytes(self, data: bytes, *, status: int = 200, ctype: str = "application/octet-stream") -> None:
        self.send_response(status)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(data)))
        self.send_header("Cache-Control", "no-cache")
        self.end_headers()
        self.wfile.write(data)

    def _requested_file(self, query: dict[str, list[str]]) -> Path | None:
        """Resolve ``?file=`` to a validated path; send the error reply and
        return None on failure."""
        if not (values := query.get("file")):
            self._send("Missing file parameter.", status=400)
            return None
        try:
            path = Path(values[0]).resolve(strict=True)
        except (OSError, RuntimeError) as e:
            self._send(f"Invalid file path: {e}", status=400)
            return None
        if not path.is_file():
            self._send("Requested path is not a regular file.", status=404)
            return None
        if not self._app.is_allowed(path):
            self._send("File is outside allowed roots.", status=403)
            return None
        return path

    def _requested_dir(self, query: dict[str, list[str]]) -> Path | None:
        """Resolve ``?path=`` (a directory) to a validated path, error reply on
        failure (mirror of :meth:`_requested_file` for folders)."""
        if not (values := query.get("path")):
            self._send("Missing path parameter.", status=400)
            return None
        try:
            path = Path(values[0]).resolve(strict=True)
        except (OSError, RuntimeError) as e:
            self._send(f"Invalid directory path: {e}", status=400)
            return None
        if not path.is_dir():
            self._send("Requested path is not a directory.", status=404)
            return None
        if not self._app.is_allowed(path):
            self._send("Directory is outside allowed roots.", status=403)
            return None
        return path

    def do_GET(self) -> None:
        parsed = urllib.parse.urlparse(self.path)
        query = urllib.parse.parse_qs(parsed.query)

        # Viewer page + first-party assets (web/)
        if (viewer := _VIEWER_FILES.get(parsed.path)) is not None:
            name, ctype = viewer
            try:
                self._send_bytes((_WEB_DIR / name).read_bytes(), ctype=ctype)
            except OSError as e:
                self._send(f"Viewer file unreadable: {_WEB_DIR / name} ({e})", status=500)
            return

        # Silence the browser's automatic icon request
        if parsed.path == "/favicon.ico":
            self.send_response(204)
            self.end_headers()
            return

        # Vendored third-party runtime (marked / MathJax / highlight.js) — offline viewer
        if parsed.path.startswith("/assets/"):
            ctype = _ASSET_CTYPE.get(suffix := Path(parsed.path).suffix.lower())
            if ctype is None:
                self._send(f"Unsupported asset type: {suffix}", status=403)
                return
            path = (_VEND_DIR / urllib.parse.unquote(parsed.path.removeprefix("/assets/"))).resolve()
            if _rel_error(path, _VEND_DIR) or not path.is_file():
                self._send("Asset not found.", status=404)
                return
            self._send_bytes(path.read_bytes(), ctype=ctype)
            return

        # Document API — markdown & source classes as JSON for the viewer
        if parsed.path == "/api/document":
            if not (path := self._requested_file(query)):
                return
            kind = _kind_of(path)
            if kind not in ("markdown", "source"):
                self._send("Unsupported document type.", status=415)
                return
            try:
                text = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                self._send("File is not valid UTF-8.", status=400)
                return
            except OSError as e:
                self._send(f"Cannot read file: {e}", status=404)
                return
            language = (
                "markdown" if kind == "markdown" else _SOURCE_LANG.get(path.suffix[1:].lower(), "plaintext")
            )
            self._send(
                json.dumps({"kind": kind, "file": str(path), "language": language, "content": text}),
                ctype="application/json; charset=utf-8",
            )
            return

        # Directory API — immediate children of a folder as relative <a> hrefs.
        # The viewer's delegated click handler decides link → document vs folder;
        # this endpoint stays cheap (no recursion) — the browser navigates.
        if parsed.path == "/api/directory":
            if not (path := self._requested_dir(query)):
                return
            show_source = query.get("show_source")[0] == "1" if query.get("show_source") else False
            listing = _dir_listing(path, show_source=show_source)
            # Up-link only when the parent is still inside allowed roots
            if (parent := path.parent) != path and self._app.is_allowed(parent.resolve()):
                listing["parent"] = "../"
            self._send(json.dumps(listing), ctype="application/json; charset=utf-8")
            return

        # Binary asset API — images in their native MIME type
        if parsed.path == "/api/asset":
            if not (path := self._requested_file(query)):
                return
            ctype = _IMAGE_MIME.get(path.suffix.lower())
            if ctype is None:
                self._send("Only configured image files may be served as assets.", status=403)
                return
            try:
                self._send_bytes(path.read_bytes(), ctype=ctype)
            except OSError as e:
                self._send(f"Cannot read image: {e}", status=404)
            return

        self._send("Not found.", status=404)


class _Server(http.server.ThreadingHTTPServer):
    """HTTP server carrying a reference to its :class:`DocumentationBrowser` owner."""

    daemon_threads = True
    allow_reuse_address = True

    def __init__(self, address: tuple[str, int], app: DocumentationBrowser) -> None:
        super().__init__(address, _Handler)
        self.app = app
